[project]
name = "classic-scaper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "babel>=2.17.0",
    "playwright>=1.55.0",
    "python-dateutil>=2.9.0.post0",
]
